name: PoissonNet

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pybind11
          sudo apt install libboost-all-dev
    
      - name: Run test build & test
        run: |
          make python_bind_test
        working-directory: src/c
      
      - name: Run partial test
        run: |
          make partial_test
        working-directory: src/c
